##
# Configuration des templates twig
#
# Ce fichier de configuration de définir pour chaque template/layout, la liste des pages qui y sont associés
##

Game:
    template: layout_game.twig
    pages:
        - game

Default:
	template: layout.twig
